- name: Run tests
  run: |
    javac -cp src src/TestTask.java
    java -cp src org.junit.runner.JUnitCore TestTask

on:
  pull_request:

jobs:
  build:
    uses: yandex-praktikum/java-kanban/.github/workflows/api-tests.yml@ci